name = input("Hello! What's you name? ")
print("Hello", name + ".")
favGame = input("What's your favorite game? ").title()
print(favGame, "sounds fun.")
favAnimal = input("What's your favorite animal? ")
print("My favorite animal is also a", favAnimal)
favFood = input("What's your favorite food? ").title()
print(favFood, "sounds delicous.")
print("Thanks for talking with me!")